#!/usr/bin/env sh

# abort on errors
set -e

# build
npm run build

# navigate into the build output directory
cd docs/.vuepress/dist

git init
git add -A
git commit -m 'deploy'

git push -f git@github.com:Pepijn98/scope-api-docs.git master:gh-pages
git push -f git@github.com:future-id/scope-api-docs.git master:gh-pages
git push -f git@github.com:future-id/scope-api.git master:gh-pages

cd -
